apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
     project: default
     source:
       repoURL: git@github.com:saintmalik/gitops-argocd.git
       targetRevision: HEAD
       path: dev
       directory:
         recurse: true
     destination:
       server: https://kubernetes.default.svc
       namespaces: default
     syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            prune: true
            selfHeal: true